import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css';


// seo keywords:
const title = "sdf90sdjsduudfs89H&U(Hh)";
const header1 = "jIUHi(*&7h8nnbyt^T6 &6)";
const para = "LKjhju9YhgbFuyt89*(UkjhIUY867UYG";



const googleTitleSearch = "https://www.google.com/search?q=sdf90sdjsduudfs89H%26U%28Hh%29&rlz=1C1CHBF_en-GBGB980GB980&sxsrf=ALiCzsYHB3CosefT0yQzYMylrPckF5PdZQ%3A1663003024895&ei=kGkfY86fNqWGhbIPgti3mAw&ved=0ahUKEwjOp7yE4Y_6AhUlQ0EAHQLsDcMQ4dUDCA4&uact=5&oq=sdf90sdjsduudfs89H%26U%28Hh%29&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECdKBAhBGABKBAhGGABQAFgAYKQEaABwAXgAgAFNiAFNkgEBMZgBAKABAqABAcABAQ&sclient=gws-wiz";
const googleHeaderSearch = "https://www.google.com/search?q=jIUHi%28*%267h8nnbyt%5ET6+%266%29&rlz=1C1CHBF_en-GBGB980GB980&sxsrf=ALiCzsZIsNMNQs4TEun_ShC-aBvfeYp7kQ%3A1663013682830&ei=MpMfY62mMpTzgAbl4IGQAQ&ved=0ahUKEwith8neiJD6AhWUOcAKHWVwABIQ4dUDCA4&uact=5&oq=jIUHi%28*%267h8nnbyt%5ET6+%266%29&gs_lcp=Cgdnd3Mtd2l6EAMyBwghEKABEApKBAhBGABKBAhGGABQAFgAYIcPaABwAHgAgAFsiAFskgEDMC4xmAEAoAECoAEBwAEB&sclient=gws-wiz";
const googleParaSearch = "https://www.google.com/search?q=LKjhju9YhgbFuyt89*%28UkjhIUY867UYG&rlz=1C1CHBF_en-GBGB980GB980&sxsrf=ALiCzsa3ZfBy_tJ5kRk_nTGapoi_la5r5A%3A1663013672647&ei=KJMfY_SOJ9eH8gKnvbboAw&ved=0ahUKEwj0wtvZiJD6AhXXg1wKHaeeDT0Q4dUDCA4&uact=5&oq=LKjhju9YhgbFuyt89*%28UkjhIUY867UYG&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABKBAhGGABQAFgAYI0BaABwAHgAgAEAiAEAkgEAmAEAoAECoAEBwAEB&sclient=gws-wiz";



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>


        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



{/* MENU: */}
<nav>

<Link href="/asldkfoiajoiajsdf8asjd9uasud879y7hUYIH">

  <a>second page</a>
</Link>
</nav>


<h1>Header 1: {header1}</h1>
<p>Para: {para}</p>








<h2>Links with search results:</h2>
<Link 
  href={googleTitleSearch}
  >
<a target="_blank">title</a>
</Link>

<br />
<Link href={googleHeaderSearch}>
<a target="_blank">header 1</a></Link>


<br />
<Link href={googleParaSearch}><a target="_blank">
  Para
  </a></Link>











  
</div>
  )
}
